# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: function.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'function.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x66unction.proto\x12\x08\x66unction\"%\n\rDeployRequest\x12\x14\n\x0c\x63ode_content\x18\x01 \x01(\t\"2\n\x0e\x44\x65ployResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"-\n\x0f\x46unctionRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x03(\t\"\"\n\x10\x46unctionResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2\xa0\x01\n\x0f\x46unctionRuntime\x12H\n\x0f\x45xecuteFunction\x12\x19.function.FunctionRequest\x1a\x1a.function.FunctionResponse\x12\x43\n\x0e\x44\x65ployFunction\x12\x17.function.DeployRequest\x1a\x18.function.DeployResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'function_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEPLOYREQUEST']._serialized_start=28
  _globals['_DEPLOYREQUEST']._serialized_end=65
  _globals['_DEPLOYRESPONSE']._serialized_start=67
  _globals['_DEPLOYRESPONSE']._serialized_end=117
  _globals['_FUNCTIONREQUEST']._serialized_start=119
  _globals['_FUNCTIONREQUEST']._serialized_end=164
  _globals['_FUNCTIONRESPONSE']._serialized_start=166
  _globals['_FUNCTIONRESPONSE']._serialized_end=200
  _globals['_FUNCTIONRUNTIME']._serialized_start=203
  _globals['_FUNCTIONRUNTIME']._serialized_end=363
# @@protoc_insertion_point(module_scope)
